apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mafin/k8sapp.git'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8sapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
