apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt ACME server URL pro production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email pro notifikace (změňte na váš email)
    email: net@jenin.cz
    # Secret pro ukládání ACME private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # HTTP01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx
