apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: k8sapp-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: registry.digitalocean.com/mafin-dev/k8sapp
    newTag: v1.0.4