name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create test database
        run: php bin/console doctrine:database:create --env=test

      - name: Run database migrations
        run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Load database fixtures
        run: php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Check Code Style
        run: composer cs:check

      - name: Run Static Analysis
        run: composer phpstan

      - name: Run Tests
        run: composer test

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_PAT }}
          password: ${{ secrets.DO_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/mafin-dev/k8sapp:latest
            registry.digitalocean.com/mafin-dev/k8sapp:${{ github.sha }}
            registry.digitalocean.com/mafin-dev/k8sapp:v1.${{ github.run_number }}

      - name: Update Kubernetes deployment
        if: success()
        run: |
          # Update image tag in deployment.yaml
          sed -i "s|image: registry.digitalocean.com/mafin-dev/k8sapp:.*|image: registry.digitalocean.com/mafin-dev/k8sapp:v1.${{ github.run_number }}|" k8s/deployment.yaml

          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Commit and push the change
          git add k8s/deployment.yaml
          git commit -m "deploy: update to v1.${{ github.run_number }} 🤖"
          git push
